prog:
	gcc -pthread prog.c -o prog

simple_test:
	./prog 2 block files/simpletest.ascii.pgm result.ascii.pmg

lena_test:
	./prog 4 numbers files/lena.ascii.pgm result.ascii.pmg

mona_lisa_test:
	./prog 8 block files/mona_lisa.ascii.pgm result.ascii.pmg


